# Changes here will be overwritten by Copier
_commit: 559fceb
_src_path: gh:LSSTDESC/RAIL-project-template
author_email: later@later.com
author_name: ''
create_example_module: false
package_name: inception
project_name: pz-rail-inception
